apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "helm-basic-chart.fullname" . }}-consumer
  name: data-consumer
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    deployment: {{ include "helm-basic-chart.fullname" . }}-consumer
  sessionAffinity: None
  type: ClusterIP
