apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: {{ include "helm-basic-chart.fullname" . }}-consumer
  name: {{ include "helm-basic-chart.fullname" . }}-consumer
spec:
  rules:
    - host: {{ .Values.consumer.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "helm-basic-chart.fullname" . }}-consumer
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - {{ .Values.consumer.host }}
      secretName: consumer-labapp-acend-ch
