apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
  labels:
    app: {{ include "helm-basic-chart.fullname" . }}-consumer
  name: {{ include "helm-basic-chart.fullname" . }}-consumer
spec:
  rules:
    - host: consumer-user00.labapp.acend.ch
      http:
        paths:
          - backend:
              service:
                name: {{ include "helm-basic-chart.fullname" . }}-consumer
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - consumer-user00.labapp.acend.ch
      secretName: consumer-labapp-acend-ch
