apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "helm-basic-chart.labels" . | nindent 4 }}
  name: {{ include "helm-basic-chart.fullname" . }}-mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
        {{- include "helm-basic-chart.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "helm-basic-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - args:
            - '--ignore-db-dir=lost+found'
          env:
            - name: MYSQL_USER
              value: acend
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mariadb-password
                  name: myapp-mariadb
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mariadb-root-password
                  name: myapp-mariadb
            - name: MYSQL_DATABASE
              value: acenddb
          image: 'registry.puzzle.ch/docker.io/mariadb:10.5'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3306
            timeoutSeconds: 1
          name: mariadb
          ports:
            - containerPort: 3306
              name: mariadb
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadb-persistent-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: myapp-helm-basic-chart
      serviceAccountName: myapp-helm-basic-chart
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: mariadb-persistent-storage
