apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  name: {{ include "helm-basic-chart.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
        {{- include "helm-basic-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm-basic-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - image: 'quay.io/acend/example-web-python:latest'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: helm-basic-chart
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          securityContext: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: myapp-helm-basic-chart
      serviceAccountName: myapp-helm-basic-chart
      terminationGracePeriodSeconds: 30
