apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
  labels:
    app: {{ include "helm-basic-chart.fullname" . }}
  name: {{ .Values.serviceName }}
spec:
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.serviceName }}
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: labapp-acend-ch
