apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "helm-basic-chart.fullname" . }}-producer
  name: {{ include "helm-basic-chart.fullname" . }}-producer
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    deployment: {{ include "helm-basic-chart.fullname" . }}-producer
  sessionAffinity: None
  type: ClusterIP
