apiVersion: v1
data:
  mariadb-password: Zm9v
  mariadb-root-password: YmFy
kind: Secret
metadata:
  labels:
    {{- include "helm-basic-chart.labels" . | nindent 4 }}
  name: {{ include "helm-basic-chart.fullname" . }}
type: Opaque
