apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "helm-basic-chart.labels" . | nindent 4 }}
  name: {{ include "helm-basic-chart.fullname" . }}-mariadb
spec:
  clusterIP: None
  clusterIPs:
    - None
  ports:
    - name: mariadb
      port: 3306
      protocol: TCP
      targetPort: mariadb
  selector:
    {{- include "helm-basic-chart.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
