apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "helm-basic-chart.labels" . | nindent 4 }}
  name: {{ include "helm-basic-chart.fullname" . }}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    {{- include "helm-basic-chart.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
